--CREATE TABLE tb_user (
--    user_id INT8 GENERATED BY DEFAULT AS IDENTITY,
--    user_name VARCHAR(255),
--    user_pass VARCHAR(255),
--    PRIMARY KEY (user_id)
--);

--
--CREATE TABLE tb_purchase (
--    purchase_id INT8 GENERATED BY DEFAULT AS IDENTITY,
--    user_id INT8,
--    purchase_date DATE,
--    PRIMARY KEY (purchase_id),
--    FOREIGN KEY (user_id) REFERENCES tb_user (user_id)
--);

--CREATE TABLE tb_product (
--    product_id INT8 GENERATED BY DEFAULT AS IDENTITY,
--    product_name VARCHAR(255),
--    product_desc VARCHAR(255),
--    purchase_date DATE,
--    PRIMARY KEY (product_id)
--);

--CREATE TABLE tb_purchase_product (
--    purchase_product_id INT8 GENERATED BY DEFAULT AS IDENTITY,
--    purchase_id INT8,
--    product_id INT8,
--    PRIMARY KEY (purchase_product_id),
--    FOREIGN KEY (purchase_id) REFERENCES tb_purchase (purchase_id),
--    FOREIGN KEY (product_id) REFERENCES tb_product (product_id)
--);

INSERT INTO tb_user( user_name, user_pass) VALUES ( 'teste', '1234');
-------------------------------------------------------

INSERT INTO tb_purchase (user_id, purchase_date)
VALUES (1, '2023-10-12');

INSERT INTO tb_purchase (user_id, purchase_date)
VALUES (1, '2023-10-12');
-------------------------------------------------------

INSERT INTO tb_product (product_name, product_desc)
VALUES ('product 1', 'Descrição do product 1');
INSERT INTO tb_product (product_name, product_desc)
VALUES ('product 2', 'Descrição do product 2');
INSERT INTO tb_product (product_name, product_desc)
VALUES ('Produto 3', 'Descrição do Produto 3');
INSERT INTO tb_product (product_name, product_desc)
VALUES ('Produto 4', 'Descrição do Produto 4');
INSERT INTO tb_product (product_name, product_desc)
VALUES ('Produto 5', 'Descrição do Produto 5');

-------------------------------------------------------

INSERT INTO tb_purchase_product (purchase_id, product_id)
VALUES (
    (SELECT purchase_id FROM tb_purchase WHERE purchase_id = 2 ),
    (SELECT product_id FROM tb_product WHERE product_id = 2)
);

INSERT INTO tb_purchase_product (purchase_id, product_id)
VALUES (
    (SELECT purchase_id FROM tb_purchase WHERE purchase_id = 2),
    (SELECT product_id FROM tb_product WHERE product_id = 1)
);

INSERT INTO tb_purchase_product (purchase_id, product_id)
VALUES (
    (SELECT purchase_id FROM tb_purchase WHERE purchase_id = 2),
    (SELECT product_id FROM tb_product WHERE product_id = 3)
);

INSERT INTO tb_purchase_product (purchase_id, product_id)
VALUES (
    (SELECT purchase_id FROM tb_purchase WHERE purchase_id = 1),
    (SELECT product_id FROM tb_product WHERE product_id = 4)
);

INSERT INTO tb_purchase_product (purchase_id, product_id)
VALUES (
    (SELECT purchase_id FROM tb_purchase WHERE purchase_id = 1),
    (SELECT product_id FROM tb_product WHERE product_id = 5)
);